services:

  keycloak:
    image: gunnaraccso/keycloak.server:21.1.1
    restart: always
    env_file:
      - ./env/keycloak.env
    ports:
      - "9001:8443"
      - "9000:8080"
    command:
      - start-dev
      - --features admin-fine-grained-authz
      - --https-certificate-file=/keycloak/config/ssl/cert.pem
      - --https-certificate-key-file=/keycloak/config/ssl/key.pem
    volumes:
      - ./ssl/cert.pem:/keycloak/config/ssl/cert.pem
      - ./ssl/key.pem:/keycloak/config/ssl/key.pem

  camunda:
    build: .
    ports: 
      - "8080:8080"
    env_file:
      - ./env/camunda.env
    depends_on:
      - keycloak
    restart: always
    volumes:
      - ./config/default.yml:/camunda/configuration/default.yml
      - ./config/production.yml:/camunda/configuration/production.yml

