spring.datasource:
  url: ${JDBC_URL:jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
  username: ${JDBC_USER:sa}
  password: ${JDBC_PASSWORD:sa}
#spring.h2.console.enabled: true

spring:
  jersey:
    application-path: /engine-rest

# Redis Session Cache not yet in use
#  session:
#    store-type: ${SESSION_STORE_TYPE:none}
#    redis.flush-mode: immediate
#  redis:
#    host: ${REDIS_HOST:localhost}
#    port: ${REDIS_PORT:6379}

camunda.bpm:
  history-level: audit
  authorization:
    enabled: true
  filter:
    create: All tasks

server:
  port: 8080
  servlet.context-path: /camunda

# Externalized Keycloak configuration
keycloak:
  # SSO Authentication requests. Send by application as redirect to the browser
  url.auth: ${KEYCLOAK_URL_AUTH:http://localhost:9000}
  # SSO Token requests. Send from the application to Keycloak
  url.token: ${KEYCLOAK_URL_TOKEN:http://localhost:9000}
  # Keycloak access for the Identity Provider plugin.
  url.plugin: ${KEYCLOAK_URL_PLUGIN:https://localhost:9001}

  # Keycloak Camunda Identity Client
  client.id: ${KEYCLOAK_CLIENT_ID:camunda-identity-service}
  client.secret: ${KEYCLOAK_CLIENT_SECRET:0ca35c49-c721-44dd-a6c2-a5e825e13c84}

# Spring Boot SSO OAuth2 Security
security:
  oauth2:
    client:
      client-id: ${keycloak.client.id}
      client-secret: ${keycloak.client.secret}
      accessTokenUri: ${keycloak.url.token}/auth/realms/camunda/protocol/openid-connect/token
      userAuthorizationUri: ${keycloak.url.auth}/auth/realms/camunda/protocol/openid-connect/auth
      scope: openid profile email
    resource:
      userInfoUri: ${keycloak.url.auth}/auth/realms/camunda/protocol/openid-connect/userinfo

logging.level.org.springframework.security: DEBUG

# Camunda Keycloak Identity Provider Plugin
plugin.identity.keycloak:
  keycloakIssuerUrl: ${keycloak.url.plugin}/auth/realms/camunda
  keycloakAdminUrl: ${keycloak.url.plugin}/auth/admin/realms/camunda
  clientId: ${keycloak.client.id}
  clientSecret: ${keycloak.client.secret}
  useEmailAsCamundaUserId: true
  useUsernameAsCamundaUserId: false
  useGroupPathAsCamundaGroupId: true
  administratorGroupName: camunda-admin
  disableSSLCertificateValidation: true